AllCops:
  NewCops: enable

Naming/MethodParameterName:
  Enabled: true
  AllowedNames:
    - x
    - y
    - z

Metrics/MethodLength:
  Enabled: true
  Max: 50

Metrics/ModuleLength:
  Enabled: true
  Max: 150

Layout/LeadingEmptyLines:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never
