AllCops:
  NewCops: enable

Layout/LeadingEmptyLines:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never

Metrics/MethodLength:
  Enabled: true
  Max: 50

Metrics/ModuleLength:
  Enabled: true
  Max: 150
