name: Ruby
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Gosu dependencies
        run: sudo apt-get update && sudo apt-get install -y libsdl2-dev libgl1-mesa-dev libfontconfig1-dev xvfb

      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Not needed with a .ruby-version file
          ruby-version: 2.7
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
      - name: Run tests
        run: |
          xvfb-run --auto-servernum bundle exec rake test
